### ISSUE TITLE
Default Startup Error

### ISSUE THREAD

**Issue by kz0** [ruippeixotog/ebay-snipe-server#10]
When using the default command 

`docker run -d -p 3647:3647 \
  -e 'EBAY_USERNAME=<your_username>' -e 'EBAY_PASSWORD=<your_password>' \
  ruippeixotog/ebay-snipe-server:0.2.2-SNAPSHOT`

the appdata dir and files aren't created

`16:21:29,317 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml],
16:21:29,317 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy],
16:21:29,317 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/docker/conf/logback.xml],
16:21:29,568 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set,
16:21:29,569 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender],
16:21:29,578 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT],
16:21:29,591 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property,
16:21:29,635 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender],
16:21:29,638 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [LOG_FILES],
16:21:29,650 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@209169911 - No compression will be used,
16:21:29,651 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@209169911 - Will use the pattern logs/app.%d{yyyy-MM-dd}.log for the active file,
16:21:29,656 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/app.%d{yyyy-MM-dd}.log'.,
16:21:29,656 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.,
16:21:29,662 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sat Mar 16 16:21:29 UTC 2019,
16:21:29,665 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property,
16:21:29,671 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOG_FILES] - Active log file name: logs/app.log,
16:21:29,671 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[LOG_FILES] - File property is set to [logs/app.log],
16:21:29,673 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[LOG_FILES] - Failed to create parent directories for [/opt/docker/logs/app.log],
16:21:29,673 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[LOG_FILES] - openFile(logs/app.log,true) call failed. java.io.FileNotFoundException: logs/app.log (No such file or directory),
	at java.io.FileNotFoundException: logs/app.log (No such file or directory),
	at 	at java.io.FileOutputStream.open0(Native Method),
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270),
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213),
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26),
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204),
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127),
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100),
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90),
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309),
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193),
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179),
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62),
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165),
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152),
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110),
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53),
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75),
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150),
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84),
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55),
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150),
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124),
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412),
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357),
	at 	at akka.event.slf4j.Logger$.apply(Slf4jLogger.scala:30),
	at 	at akka.event.slf4j.SLF4JLogging.log(Slf4jLogger.scala:19),
	at 	at akka.event.slf4j.SLF4JLogging.log$(Slf4jLogger.scala:19),
	at 	at akka.event.slf4j.Slf4jLogger.log$lzycompute(Slf4jLogger.scala:54),
	at 	at akka.event.slf4j.Slf4jLogger.log(Slf4jLogger.scala:54),
	at 	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:92),
	at 	at akka.actor.Actor.aroundReceive(Actor.scala:517),
	at 	at akka.actor.Actor.aroundReceive$(Actor.scala:515),
	at 	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:54),
	at 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592),
	at 	at akka.actor.ActorCell.invoke(ActorCell.scala:561),
	at 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258),
	at 	at akka.dispatch.Mailbox.run(Mailbox.scala:225),
	at 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235),
	at 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260),
	at 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339),
	at 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979),
	at 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107),
16:21:29,674 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.ruippeixotog] to DEBUG,
16:21:29,674 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO,
16:21:29,674 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT],
16:21:29,675 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.,
16:21:29,675 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@59bf93ec - Registering current configuration as safe fallback point,
,
2019-03-16 16:21:29,683 INFO  Slf4jLogger - Slf4jLogger started,
2019-03-16 16:21:30,049 INFO  SnipeServer$ - Logging in into eBay,
2019-03-16 16:21:30,050 DEBUG EbayLoginManager - Getting the sign in cookie for ebay.com,
2019-03-16 16:21:35,097 INFO  EbayLoginManager - Login successful,
2019-03-16 16:21:35,103 INFO  SnipeServer$ - Using appdata/snipes.json for persisting snipe data,`

this is the error when adding an item

`
2019-03-16 16:29:44,454 INFO  SnipeServer$ - POST /auction/362574339937/snipe {"auctionId":"362574339937","bid":630},
2019-03-16 16:29:46,816 ERROR ActorSystemImpl - Error during processing of request: 'appdata/snipes.json (No such file or directory)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler
java.io.FileNotFoundException: appdata/snipes.json (No such file or directory)`

**Comment by ruippeixotog** [comment]
@kz0 the Docker image does not seem to handle correctly cases where you don't map the two volumes to host folders.

I'll fix this in the next days; in the meanwhile, you can use the image by specifying `-v '<path_to_appdata_in_host>:/opt/docker/appdata' -v '<path_to_logs_in_host>:/opt/docker/logs'` when running the image.

**Comment by ruippeixotog** [comment]
I just released v0.2.2 of the image with this issue fixed 👍
