### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by bthome** [ruippeixotog/ebay-snipe-server#2]
Something happened in the last couple of days.  Using docker version.  Server is not listening on the port anymore.

STDERR

Exception in thread "main" java.lang.IllegalArgumentException: Data key must not be empty
    at org.jsoup.helper.Validate.notEmpty(Validate.java:102)
    at org.jsoup.helper.HttpConnection$KeyVal.key(HttpConnection.java:874)
    at org.jsoup.helper.HttpConnection$KeyVal.create(HttpConnection.java:864)
    at org.jsoup.helper.HttpConnection.data(HttpConnection.java:143)
    at net.ruippeixotog.scalascraper.browser.Browser.post(Browser.scala:20)
    at net.ruippeixotog.ebaysniper.ebay.EbayLoginManager.forceLogin(EbayLoginManager.scala:30)
    at net.ruippeixotog.ebaysniper.ebay.EbayClient.login(EbayClient.scala:26)
    at net.ruippeixotog.ebaysniper.SnipeServer$.delayedEndpoint$net$ruippeixotog$ebaysniper$SnipeServer$1(SnipeServer.scala:34)
    at net.ruippeixotog.ebaysniper.SnipeServer$delayedInit$body.apply(SnipeServer.scala:17)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at net.ruippeixotog.ebaysniper.SnipeServer$.main(SnipeServer.scala:17)
    at net.ruippeixotog.ebaysniper.SnipeServer.main(SnipeServer.scala)

APP.LOG
2016-06-25 18:22:56,684 INFO    Slf4jLogger Slf4jLogger started
2016-06-25 18:22:56,703 INFO    SnipeServer$    Logging in into eBay
2016-06-25 18:22:56,703 DEBUG   EbayLoginManager    Getting the sign in cookie for ebay.com
2016-06-25 19:03:51,364 INFO    Slf4jLogger Slf4jLogger started
2016-06-25 19:03:51,380 INFO    SnipeServer$    Logging in into eBay
2016-06-25 19:03:51,381 DEBUG   EbayLoginManager    Getting the sign in cookie for ebay.com

**Comment by ruippeixotog** [comment]
Hi @bthome! It seems that the server had an issue fetching the sign-in HTML form and did an invalid POST request because of that.

Unfortunately, the Docker version is a bit old and doesn't reflect the latest code base. I bumped the main dependency of this project, `scala-scraper`, to its first stable release and had some shortcomings arising from interfaces that changed. I intend to work a bit on these projects this weekend and update the `ebay-snipe-server` Docker image.

**Comment by ruippeixotog** [comment]
Hi! I have just updated the Docker image with the latest code on `master`. Can you please pull the new version and see if this problem occurs again?

**Comment by bthome** [comment]
Pulled the source..recompiled...installed and now working.  Thank you for the update.
